# Find the number of distinct terms in the sequence generated by a^b for
# 2 <= a <= 100, 2 <= b < 100

LOW = 2
HIGH = 100

def countTerm():
    sequence = set()
    numDistinct = 0
    
    for a in range(LOW, HIGH + 1):
        power = a
        for b in range(LOW, HIGH + 1):
            power *= a
            if not (power in sequence):
                numDistinct += 1
                sequence.add(power)

    return numDistinct
